YAKU_ORDER = {
    "tsumatch", "pinfu", "iipeikou", "tanyao", "yakuhai", "sangenpai",
    "chanta", "sanshoku_doujun", "ittsu", "toitoi", "sanshoku_doukou",
    "sankantsu", "honroutou", "honitsu", "junchan", "ryanpeikou",
    "chinitsu", "daisangen", "daisuushii", "tsuuiisou", "chinroutou",
    "ryuuiisou", "suukantsu", "kazoe_yakuman", "dora", "akadora"
}

YAKU_NAMES_EN = {
    tsumatch        = "Tsumatch",
    pinfu           = "All Runs",
    iipeikou        = "Twin Runs",
    tanyao          = "All Simples",
    yakuhai         = "Round Wind",
    sangenpai       = "Dragons",
    chanta          = "Half Outside",
    sanshoku_doujun = "Triple Runs",
    ittsu           = "Pure Straight",
    toitoi          = "All Triplets",
    sanshoku_doukou = "Triple Triplets",
    sankantsu       = "Triple Quads",
    honroutou       = "No Simples",
    honitsu         = "Half Flush",
    junchan         = "Full Outside",
    ryanpeikou      = "Twice Twin Runs",
    chinitsu        = "Full Flush",
    daisangen       = "Three Dragons",
    daisuushii      = "Four Winds",
    tsuuiisou       = "All Honors",
    chinroutou      = "All Terminals",
    ryuuiisou       = "All Green",
    suukantsu       = "Four Quads",
    kazoe_yakuman   = "Counted Yakuman",
    dora            = "Dora",
    akadora         = "Red Dora"
}

YAKU_NAMES_JA = {
    tsumatch        = "Tsumatch",
    pinfu           = "Pinfu",
    iipeikou        = "Iipeikou",
    tanyao          = "Tanyao",
    yakuhai         = "Yakuhai",
    sangenpai       = "Yakuhai",
    chanta          = "Chanta",
    sanshoku_doujun = "Sanshoku Doujun",
    ittsu           = "Ittsu",
    toitoi          = "Toitoi",
    sanshoku_doukou = "Sanshoku Doukou",
    sankantsu       = "Sankantsu",
    honroutou       = "Honroutou",
    honitsu         = "Honitsu",
    junchan         = "Junchan",
    ryanpeikou      = "Ryanpeikou",
    chinitsu        = "Chinitsu",
    daisangen       = "Daisangen",
    daisuushii      = "Daisuushii",
    tsuuiisou       = "Tsuuiisou",
    chinroutou      = "Chinroutou",
    ryuuiisou       = "Ryuuiisou",
    suukantsu       = "Suukantsu",
    kazoe_yakuman   = "Kazoe Yakuman",
    dora            = "Dora",
    akadora         = "Akadora"
}
